import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";

import { RouterOutputs, api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { LoadingPage } from "@/components/ui/spinner";
import { redirect, useRouter } from "next/navigation";

const SchedulePostWizard = () => {
  const { user, isSignedIn } = useUser();

  if (!isSignedIn) {
    return null;
  }

  return (
    <div className="flex w-full gap-4">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        width={80}
        height={80}
        className="rounded-full"
      />
      <input
        type="text"
        placeholder="Type something..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn, user } = useUser();
  const router = useRouter();

  if (!userLoaded) {
    return <div />;
  }

  if (userLoaded && isSignedIn) {
    router.push("/dashboard");
  }

  return (
    <>
      <Head>
        <title>SocialMatic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isSignedIn && "signed in"}
        <div className="flex justify-center">
          <SignInButton>
            <Button>Sign In</Button>
          </SignInButton>
        </div>
      </main>
    </>
  );
}
