import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Dashboard from "~/components/Dashboard";

import { RouterOutputs, api } from "~/utils/api";

const SchedulePostWizard = () => {
  const { user, isSignedIn } = useUser();

  if (!isSignedIn) {
    return null;
  }

  return (
    <div className="flex w-full gap-4">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        width={80}
        height={80}
        className="rounded-full"
      />
      <input
        type="text"
        placeholder="Type something..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  console.log(user);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Something went wrong</div>;
  }

  return (
    <>
      <Head>
        <title>SocialMatic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
      {/* <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-200 md:max-w-2xl">
          <div className="flex border-b border-slate-200 p-4">
            <div className="flex justify-center">
              {!user.isSignedIn && <SignInButton />}
            </div>
            {user.isSignedIn && <SchedulePostWizard />}
          </div>
          <div className="flex flex-col">
            {data.map((fullPost) => (
              <PostView key={fullPost.post.id} {...fullPost} />
            ))}
          </div>
        </div>
      </main> */}
    </>
  );
}
